# training params
max_epochs: 100
opt: 'adam'
learning_rate: 0.001 # 1e-3

# data parameters:
data_mode: 'full'
shuffle: False
val_split: 0.1
random_labelling: False
n_classes: 2
batch_size: 512
return_indicies: True
persistent_workers: True

# architecture
arch: 'resnet18'

# task params
task_out_type: 'class'
task_type: 'emb'
emb_lin_task: 'learned'

# other
seed: 0
check_val_every_n_epoch: 10
